### ISSUE TITLE
build documentation 

### ISSUE THREAD

**Issue by daveyostcom** [practicalswift/osx#1]
Is there any documentation on how to build this stuff? I'm trying to build file_utils/df and it isn't finding a header file. Are all the builds going to have problems like this?

**Comment by practicalswift** [comment]
@daveyostcom What commands are you trying and what is the error message you are getting?

A simple `xcodebuild` should do the trick in the general case :-)

**Comment by daveyostcom** [comment]
I think I was trying to build in the Xcode app.

**Comment by practicalswift** [comment]
@daveyostcom Let me know if you can reproduce the issue using `xcodebuild` and I'll re-open this issue :-)
